apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tgshm4p6m-nodejs 
  janus-idp.io/tekton: tgshm4p6m-nodejs
  backstage.io/kubernetes-id: tgshm4p6m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tgshm4p6m-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml